// <auto-generated />
using System;
using ApiCatalogoAulas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiCatalogoAulas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211230010703_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("ApiCatalogoAulas.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2022, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 1,
                            Nome = ".Net Core"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 1,
                            Nome = "C# MVC"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 1,
                            Nome = "Web API .Net"
                        },
                        new
                        {
                            Id = 4,
                            Data = new DateTime(2022, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 2,
                            Nome = "React.JS"
                        },
                        new
                        {
                            Id = 5,
                            Data = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 2,
                            Nome = "React Native"
                        },
                        new
                        {
                            Id = 6,
                            Data = new DateTime(2022, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 2,
                            Nome = "Html 5 e Css 3"
                        },
                        new
                        {
                            Id = 7,
                            Data = new DateTime(2022, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 3,
                            Nome = "Kubernetes"
                        },
                        new
                        {
                            Id = 8,
                            Data = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModuloId = 3,
                            Nome = "Cloud"
                        });
                });

            modelBuilder.Entity("ApiCatalogoAulas.Models.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Modulos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Devops"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
